export interface DistrictForPhoto {
  city: string;
  districts: {
    value: string;
    text: string;
  }[];
}

export default [
  {
    city: '서울특별시',
    districts: [
      { value: '1101', text: '종로구' },
      { value: '1104', text: '중구성동구갑' },
      { value: '1102', text: '중구성동구을' },
      { value: '1103', text: '용산구' },
      { value: '1105', text: '광진구갑' },
      { value: '1105', text: '광진구을' },
      { value: '1106', text: '동대문구갑' },
      { value: '1106', text: '동대문구을' },
      { value: '1107', text: '중랑구갑' },
      { value: '1107', text: '중랑구을' },
      { value: '1108', text: '성북구갑' },
      { value: '1108', text: '성북구을' },
      { value: '1109', text: '강북구갑' },
      { value: '1109', text: '강북구을' },
      { value: '1110', text: '도봉구갑' },
      { value: '1110', text: '도봉구을' },
      { value: '1111', text: '노원구갑' },
      { value: '1111', text: '노원구을' },
      { value: '1111', text: '노원구병' },
      { value: '1112', text: '은평구갑' },
      { value: '1112', text: '은평구을' },
      { value: '1113', text: '서대문구갑' },
      { value: '1113', text: '서대문구을' },
      { value: '1114', text: '마포구갑' },
      { value: '1114', text: '마포구을' },
      { value: '1115', text: '양천구갑' },
      { value: '1115', text: '양천구을' },
      { value: '1116', text: '강서구갑' },
      { value: '1116', text: '강서구을' },
      { value: '1116', text: '강서구병' },
      { value: '1117', text: '구로구갑' },
      { value: '1117', text: '구로구을' },
      { value: '1118', text: '금천구' },
      { value: '1119', text: '영등포구갑' },
      { value: '1119', text: '영등포구을' },
      { value: '1120', text: '동작구갑' },
      { value: '1120', text: '동작구을' },
      { value: '1121', text: '관악구갑' },
      { value: '1121', text: '관악구을' },
      { value: '1122', text: '서초구갑' },
      { value: '1122', text: '서초구을' },
      { value: '1123', text: '강남구갑' },
      { value: '1123', text: '강남구을' },
      { value: '1123', text: '강남구병' },
      { value: '1124', text: '송파구갑' },
      { value: '1124', text: '송파구을' },
      { value: '1124', text: '송파구병' },
      { value: '1125', text: '강동구갑' },
      { value: '1125', text: '강동구을' },
    ],
  },
  {
    city: '부산광역시',
    districts: [
      { value: '2604', text: '중구영도구' },
      { value: '2602', text: '서구동구' },
      { value: '2605', text: '부산진구갑' },
      { value: '2605', text: '부산진구을' },
      { value: '2606', text: '동래구' },
      { value: '2607', text: '남구갑' },
      { value: '2607', text: '남구을' },
      { value: '2608', text: '북구강서구갑' },
      { value: '2613', text: '북구강서구을' },
      { value: '2609', text: '해운대구갑' },
      { value: '2609', text: '해운대구을' },
      { value: '2611', text: '사하구갑' },
      { value: '2611', text: '사하구을' },
      { value: '2612', text: '금정구' },
      { value: '2614', text: '연제구' },
      { value: '2615', text: '수영구' },
      { value: '2616', text: '사상구' },
      { value: '2610', text: '기장군' },
    ],
  },
  {
    city: '대구광역시',
    districts: [
      { value: '2701', text: '중구남구' },
      { value: '2702', text: '동구갑' },
      { value: '2702', text: '동구을' },
      { value: '2703', text: '서구' },
      { value: '2705', text: '북구갑' },
      { value: '2705', text: '북구을' },
      { value: '2706', text: '수성구갑' },
      { value: '2706', text: '수성구을' },
      { value: '2707', text: '달서구갑' },
      { value: '2707', text: '달서구을' },
      { value: '2707', text: '달서구병' },
      { value: '2708', text: '달성군' },
    ],
  },
  {
    city: '인천광역시',
    districts: [
      { value: '2801', text: '중구강화군옹진군' },
      { value: '2803', text: '동구미추홀구갑' },
      { value: '2803', text: '동구미추홀구을' },
      { value: '2804', text: '연수구갑' },
      { value: '2804', text: '연수구을' },
      { value: '2805', text: '남동구갑' },
      { value: '2805', text: '남동구을' },
      { value: '2806', text: '부평구갑' },
      { value: '2806', text: '부평구을' },
      { value: '2807', text: '계양구갑' },
      { value: '2807', text: '계양구을' },
      { value: '2808', text: '서구갑' },
      { value: '2808', text: '서구을' },
    ],
  },
  {
    city: '광주광역시',
    districts: [
      { value: '2903', text: '동구남구갑' },
      { value: '2901', text: '동구남구을' },
      { value: '2902', text: '서구갑' },
      { value: '2902', text: '서구을' },
      { value: '2904', text: '북구갑' },
      { value: '2904', text: '북구을' },
      { value: '2905', text: '광산구갑' },
      { value: '2905', text: '광산구을' },
    ],
  },
  {
    city: '대전광역시',
    districts: [
      { value: '3001', text: '동구' },
      { value: '3002', text: '중구' },
      { value: '3003', text: '서구갑' },
      { value: '3003', text: '서구을' },
      { value: '3004', text: '유성구갑' },
      { value: '3004', text: '유성구을' },
      { value: '3005', text: '대덕구' },
    ],
  },
  {
    city: '울산광역시',
    districts: [
      { value: '3101', text: '중구' },
      { value: '3102', text: '남구갑' },
      { value: '3102', text: '남구을' },
      { value: '3103', text: '동구' },
      { value: '3104', text: '북구' },
      { value: '3105', text: '울주군' },
    ],
  },
  {
    city: '세종특별자치시',
    districts: [
      { value: '5101', text: '세종특별자치시갑' },
      { value: '5101', text: '세종특별자치시을' },
    ],
  },
  {
    city: '경기도',
    districts: [
      { value: '4101', text: '수원시갑' },
      { value: '4102', text: '수원시을' },
      { value: '4103', text: '수원시병' },
      { value: '4104', text: '수원시정' },
      { value: '4102', text: '수원시무' },
      { value: '4105', text: '성남시수정구' },
      { value: '4106', text: '성남시중원구' },
      { value: '4107', text: '성남시분당구갑' },
      { value: '4107', text: '성남시분당구을' },
      { value: '4108', text: '의정부시갑' },
      { value: '4108', text: '의정부시을' },
      { value: '4109', text: '안양시만안구' },
      { value: '4110', text: '안양시동안구갑' },
      { value: '4110', text: '안양시동안구을' },
      { value: '4111', text: '부천시갑' },
      { value: '4111', text: '부천시을' },
      { value: '4112', text: '부천시병' },
      { value: '4113', text: '부천시정' },
      { value: '4114', text: '광명시갑' },
      { value: '4114', text: '광명시을' },
      { value: '4115', text: '평택시갑' },
      { value: '4115', text: '평택시을' },
      { value: '4117', text: '동두천시연천군' },
      { value: '4118', text: '안산시상록구갑' },
      { value: '4118', text: '안산시상록구을' },
      { value: '4119', text: '안산시단원구갑' },
      { value: '4119', text: '안산시단원구을' },
      { value: '4120', text: '고양시갑' },
      { value: '4120', text: '고양시을' },
      { value: '4121', text: '고양시병' },
      { value: '4122', text: '고양시정' },
      { value: '4123', text: '의왕시과천시' },
      { value: '4125', text: '구리시' },
      { value: '4126', text: '남양주시갑' },
      { value: '4126', text: '남양주시을' },
      { value: '4126', text: '남양주시병' },
      { value: '4127', text: '오산시' },
      { value: '4129', text: '시흥시갑' },
      { value: '4129', text: '시흥시을' },
      { value: '4130', text: '군포시' },
      { value: '4131', text: '하남시' },
      { value: '4135', text: '용인시갑' },
      { value: '4137', text: '용인시을' },
      { value: '4136', text: '용인시병' },
      { value: '4137', text: '용인시정' },
      { value: '4132', text: '파주시갑' },
      { value: '4132', text: '파주시을' },
      { value: '4134', text: '이천시' },
      { value: '4138', text: '안성시' },
      { value: '4139', text: '김포시갑' },
      { value: '4139', text: '김포시을' },
      { value: '4128', text: '화성시갑' },
      { value: '4128', text: '화성시을' },
      { value: '4128', text: '화성시병' },
      { value: '4140', text: '광주시갑' },
      { value: '4140', text: '광주시을' },
      { value: '4116', text: '양주시' },
      { value: '4141', text: '포천시가평군' },
      { value: '4133', text: '여주시양평군' },
    ],
  },
  {
    city: '강원도',
    districts: [
      { value: '4201', text: '춘천시철원군화천군양구군갑' },
      { value: '4201', text: '춘천시철원군화천군양구군을' },
      { value: '4202', text: '원주시갑' },
      { value: '4202', text: '원주시을' },
      { value: '4203', text: '강릉시' },
      { value: '4204', text: '동해시태백시삼척시정선군' },
      { value: '4208', text: '속초시인제군고성군양양군' },
      { value: '4214', text: '홍천군횡성군영월군평창군' },
    ],
  },
  {
    city: '충청북도',
    districts: [
      { value: '4301', text: '청주시상당구' },
      { value: '4302', text: '청주시서원구' },
      { value: '4302', text: '청주시흥덕구' },
      { value: '4306', text: '청주시청원구' },
      { value: '4303', text: '충주시' },
      { value: '4304', text: '제천시단양군' },
      { value: '4307', text: '보은군옥천군영동군괴산군' },
      { value: '4310', text: '증평군진천군음성군' },
    ],
  },
  {
    city: '충청남도',
    districts: [
      { value: '4401', text: '천안시갑' },
      { value: '4401', text: '천안시을' },
      { value: '4401', text: '천안시병' },
      { value: '4402', text: '공주시부여군청양군' },
      { value: '4403', text: '보령시서천군' },
      { value: '4404', text: '아산시갑' },
      { value: '4404', text: '아산시을' },
      { value: '4405', text: '서산시태안군' },
      { value: '4409', text: '논산시계룡시금산군' },
      { value: '4416', text: '당진시' },
      { value: '4413', text: '홍성군예산군' },
    ],
  },
  {
    city: '전라북도',
    districts: [
      { value: '4501', text: '전주시갑' },
      { value: '4501', text: '전주시을' },
      { value: '4502', text: '전주시병' },
      { value: '4503', text: '군산시' },
      { value: '4505', text: '익산시갑' },
      { value: '4505', text: '익산시을' },
      { value: '4507', text: '정읍시고창군' },
      { value: '4508', text: '남원시임실군순창군' },
      { value: '4509', text: '김제시부안군' },
      { value: '4510', text: '완주군진안군무주군장수군' },
    ],
  },
  {
    city: '전라남도',
    districts: [
      { value: '4601', text: '목포시' },
      { value: '4602', text: '여수시갑' },
      { value: '4602', text: '여수시을' },
      { value: '4604', text: '순천시광양시곡성군구례군갑' },
      { value: '4607', text: '순천시광양시곡성군구례군을' },
      { value: '4606', text: '나주시화순군' },
      { value: '4622', text: '담양군함평군영광군장성군' },
      { value: '4612', text: '고흥군보성군장흥군강진군' },
      { value: '4618', text: '해남군완도군진도군' },
      { value: '4621', text: '영암군무안군신안군' },
    ],
  },
  {
    city: '경상북도',
    districts: [
      { value: '4701', text: '포항시북구' },
      { value: '4702', text: '포항시남구울릉군' },
      { value: '4704', text: '경주시' },
      { value: '4705', text: '김천시' },
      { value: '4706', text: '안동시예천군' },
      { value: '4707', text: '구미시갑' },
      { value: '4707', text: '구미시을' },
      { value: '4708', text: '영주시영양군봉화군울진군' },
      { value: '4709', text: '영천시청도군' },
      { value: '4710', text: '상주시문경시' },
      { value: '4713', text: '경산시' },
      { value: '4719', text: '군위군의성군청송군영덕군' },
      { value: '4717', text: '고령군성주군칠곡군' },
    ],
  },
  {
    city: '경상남도',
    districts: [
      { value: '4801', text: '창원시의창구' },
      { value: '4801', text: '창원시성산구' },
      { value: '4802', text: '창원시마산합포구' },
      { value: '4802', text: '창원시마산회원구' },
      { value: '4804', text: '창원시진해구' },
      { value: '4803', text: '진주시갑' },
      { value: '4803', text: '진주시을' },
      { value: '4805', text: '통영시고성군' },
      { value: '4807', text: '사천시남해군하동군' },
      { value: '4808', text: '김해시갑' },
      { value: '4808', text: '김해시을' },
      { value: '4809', text: '밀양시의령군함안군창녕군' },
      { value: '4810', text: '거제시' },
      { value: '4814', text: '양산시갑' },
      { value: '4814', text: '양산시을' },
      { value: '4819', text: '산청군함양군거창군합천군' },
    ],
  },
  {
    city: '제주특별자치도',
    districts: [
      { value: '4901', text: '제주시갑' },
      { value: '4901', text: '제주시을' },
      { value: '4902', text: '서귀포시' },
    ],
  },
];
